version: 2
jobs:
    build:
      docker:
        - image: kubos/kubos-linux-dev:latest
          environment:
            KUBOS_BOARD: $KUBOS_BOARD
      working_directory: ~/project/kubos-linux-build
      steps:
        - checkout
        - run: ./build.sh | tee full_build.log
        - store_artifacts:
            path: full_build.log
            destination: artifacts
        - store_artifacts:
            path: ../buildroot-2017.02.8/output/images/kubos-linux.tar.gz
            destination: artifacts