version: 2
jobs:
    build:
      docker:
        - image: kubos/kubos-linux-dev:latest
          environment:
            KUBOS_BOARD: $KUBOS_BOARD
      working_directory: ~/project/kubos-linux-build
      steps:
        - checkout
        # Build OS
        - run: ./build.sh | tee full_build.log
        # Build base kpack file
        - run: cd tools; ./kubos-package.sh -k -t $KUBOS_BOARD -v base
        # Build Aux SD image
        - run: cd tools; ./format-aux.sh
        - store_artifacts:
            path: full_build.log
            destination: full_build.log
        - store_artifacts:
            path: ../buildroot-2017.02.8/output/images/kubos-linux.tar.gz
            destination: kubos-linux.tar.gz
        - store_artifacts:
            path: tools/aux-sd.tar.gz
            destination: aux-sd.tar.gz