version: 2
jobs:
    build_bbb:
      docker:
        - image: kubos/kubos-linux-dev:latest
      environment:
        KUBOS_BOARD: beaglebone-black
      working_directory: ~/project/kubos-linux-build
      steps:
        - checkout
        - run: ./tools/build-ci.sh | tee full_build.log
        - store_artifacts:
            path: full_build.log
            destination: Beaglebone-Black/full_build.log
        - store_artifacts:
            path: output/beaglebone-black
            destination: Beaglebone-Black
    build_mbm2:
      docker:
        - image: kubos/kubos-linux-dev:latest
      environment:
        KUBOS_BOARD: pumpkin-mbm2
      working_directory: ~/project/kubos-linux-build
      steps:
        - checkout
        - load_deps
        - run: ./tools/build-ci.sh | tee full_build.log
        - store_artifacts:
            path: full_build.log
            destination: Pumpkin-MBM2/full_build.log
        - store_artifacts:
            path: output/pumpkin-mbm2
            destination: Pumpkin-MBM2
    build_iobc:
      docker:
        - image: kubos/kubos-linux-dev:latest
      environment:
        KUBOS_BOARD: at91sam9g20isis
      working_directory: ~/project/kubos-linux-build
      steps:
        - checkout
        - run: ./tools/build-ci.sh | tee full_build.log
        - store_artifacts:
            path: full_build.log
            destination: iOBC/full_build.log
        - store_artifacts:
            path: output/at91sam9g20isis
            destination: iOBC
            
workflows:
  version: 2
  build:
    jobs:
      - build_bbb:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: master
      - build_mbm2:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - build_iobc:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
